const templatesTypes = {
  FETCH_TEMPLATES_START: 'FETCH_TEMPLATES_START',
  FETCH_TEMPLATES_SUCCESS: 'FETCH_TEMPLATES_SUCCESS',
  FETCH_TEMPLATES_FAILURE: 'FETCH_TEMPLATES_FAILURE',
  CREATE_TEMPLATE_START: 'CREATE_TEMPLATE_START',
  CREATE_TEMPLATE_SUCCESS: 'CREATE_TEMPLATE_SUCCESS',
  CREATE_TEMPLATE_FAILURE: 'CREATE_TEMPLATE_FAILURE',
  DELETE_TEMPLATE_START: 'DELETE_TEMPLATE_START',
  DELETE_TEMPLATE_SUCCESS: 'DELETE_TEMPLATE_SUCCESS',
  DELETE_TEMPLATE_FAILURE: 'DELETE_TEMPLATE_FAILURE',
  DEPLOYMENT_TEMPLATE_DONE: 'DEPLOYMENT_TEMPLATE_DONE',
};

export default templatesTypes;
